# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-03 18:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('telefone', models.CharField(max_length=10)),
                ('cpf', models.IntegerField(verbose_name=11)),
            ],
        ),
        migrations.CreateModel(
            name='Escritorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_escritorio', models.CharField(max_length=120)),
                ('servico', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='ItemAgenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.TimeField()),
                ('data', models.DateField()),
                ('situacao', models.CharField(choices=[('A', 'Agendada'), ('R', 'Realizada'), ('C', 'Cancelada')], max_length=1)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_cliente', to='agenda.Cliente')),
                ('escritorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_agenda', to='agenda.Escritorio')),
            ],
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('telefone', models.CharField(max_length=10)),
                ('profissão', models.CharField(max_length=120)),
                ('disponivel', models.BooleanField()),
                ('escritorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profissionais', to='agenda.Escritorio')),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=3)),
                ('andar', models.CharField(max_length=2)),
                ('escritorio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salas', to='agenda.Escritorio')),
            ],
        ),
        migrations.AddField(
            model_name='itemagenda',
            name='profissional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_profissional', to='agenda.Profissional'),
        ),
    ]
