# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-03 18:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemagenda',
            name='escritorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_escritorio', to='agenda.Escritorio'),
        ),
    ]
