# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-25 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_auto_20170703_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemagenda',
            name='situacao',
            field=models.CharField(choices=[('A', 'Agendado'), ('R', 'Realizado'), ('C', 'Cancelado')], default='A', max_length=1),
        ),
    ]
