# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-25 20:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_auto_20170725_1812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profissional',
            old_name='profissão',
            new_name='profissao',
        ),
    ]
